parameters:
  kbrw.content.type.normalizer.class: "Kbrw\RiakBundle\Service\Content\ContentTypeNormalizer"
  kbrw.content.type.normalizer.types:
    "application/xml": [xml, xsd, xslt]
    "application/json": [json]
    "text/plain": [txt]
  
  kbrw.guzzle.client.provider.class: "Kbrw\RiakBundle\Service\WebserviceClient\Guzzle\SimpleGuzzleClientProvider"
  
  kbrw.riak.bucket.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakBucketServiceClient"
  kbrw.riak.bucket.route: "{protocol}://{domain}:{port}/riak/{bucket}{?keys,props}"
  
  kbrw.riak.kv.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakKVServiceClient"
  kbrw.riak.kv.route: "{protocol}://{domain}:{port}/riak/{bucket}/{id}{?r,w,dw}"
  
  kbrw.riak.search.class: "Kbrw\RiakBundle\Service\WebserviceClient\Riak\RiakSearchServiceClient"
  kbrw.riak.search.route: "{protocol}://{domain}:{port}/solr/{bucket}/select{?q,start,rows,df,q.op,sort,wt,filter,fl,additionalParameters*}"
  
services:
  kbrw.content.type.normalizer:
    class: "%kbrw.content.type.normalizer.class%"
    arguments: [%kbrw.content.type.normalizer.types%]
    
  kbrw.guzzle.client.provider:
    class: "%kbrw.guzzle.client.provider.class%"
      
  kbrw.riak.bucket:
    class: "%kbrw.riak.bucket.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.bucket.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]
      
  kbrw.riak.kv:
    class: "%kbrw.riak.kv.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.kv.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setContentTypeNormalizer, [ "@kbrw.content.type.normalizer" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]
      
  kbrw.riak.search:
    class: "%kbrw.riak.search.class%"
    calls:
      - [setRoute,                 [ "%kbrw.riak.search.route%" ] ]
      - [setLogger,                [ "@logger" ] ]
      - [setSerializer,            [ "@jms_serializer" ] ]
